### ISSUE TITLE
When enable (context-menu-mode 1) globally, mouse right menu not appear when click mouse right button.

### ISSUE THREAD

**Issue by zw963** [yoshiki/yaml-mode#112]
Following is a example: (work on emacs 28.1 later)

```cl
(setq-default context-menu-functions
              '(context-menu-hideshow
                context-menu-show-git-message
                context-menu-split/close-window
                occur-context-menu
                context-menu-region
                ))

(context-menu-mode t)
```

In most of mode, will appear a right menu when click mouse right button.

![image](https://github.com/yoshiki/yaml-mode/assets/549126/d53db635-5a25-4ec7-977f-63127dfb5fc8)

But, this menu never appear on both yaml-mode and yaml-ts-mode even context-menu-mode was enabled.

Thanks.

**Comment by wasamasa** [comment]
This appears to be the fault of your `context-menu-functions` customization. With the default setting, I get a right click menu for both `emacs-lisp-mode` and `yaml-mode` buffers. But with your setting, I do not get a right click menu in either mode.

Some basic debugging shows that this happens for me because the following three functions do not exist in Emacs:

- `context-menu-hideshow`
- `context-menu-show-git-message`
- `context-menu-split/close-window`

This isn't anything yaml-mode can do a thing about, so please fix your own configuration.

**Comment by zw963** [comment]
Hi, @wasamasa , sorry for my not working code, those missing functions defined my myself, please check [here](https://github.com/zw963/.emacs.d/blob/master/plugins/prog-mode/context-menu-mode_init.el)

I never thought this issue caused by functions,i reduce code to following:

```cl
(setq-default context-menu-functions
              '(context-menu-hideshow
                ))

(defun context-menu-hideshow (menu click)
  "Populate MENU with `hideshow' commands."
  (save-excursion
    (mouse-set-point click)
    (if (hs-already-hidden-p)
        (define-key-after menu [hs-show-block]
          '(menu-item "Show block"
                      (lambda (click) (interactive "e")
                        (save-excursion
                          (mouse-set-point click)
                          (hs-show-block)))))
      (define-key-after menu [hs-hide-block]
        '(menu-item "Hide block"
                    (lambda (click) (interactive "e")
                      (save-excursion
                        (mouse-set-point click)
                        (hs-hide-block)))))))
  (define-key-after menu [hs-separator]
    menu-bar-separator)
  menu)

(context-menu-mode t)
```

Above config can show a right menu like this: (please check screenshot)

![image](https://github.com/yoshiki/yaml-mode/assets/549126/e40fee1d-1f80-40f4-9fde-68cc37cccbbf)

But, nothing when work with yaml-mode

So, there is something in yaml-mode broken this?

**Comment by wasamasa** [comment]
No, this is `context-menu-hideshow` being broken. It will only add context menu entries if it runs without errors. For example, if `hs-minor-mode` hasn't been enabled, `context-menu-hideshow` will fail with an error because `hs-already-hidden-p` is not defined yet. While `yaml-mode` does not have support for `hs-minor-mode`, your function should still be written in a better way to handle this gracefully instead of just not generating a context menu.

**Comment by zw963** [comment]
Okay, thanks, i fixed it. i don't know why hs-minor-mode not work with yaml-mode, but anyway i add a new menu function, use yafolding, it works!

```cl
(setq-default context-menu-functions
              '(
			  context-menu-yafolding
                ))

;; For use with yaml-mode
(defun context-menu-yafolding (menu click)
  "Populate MENU with `hideshow' commands."
  (save-excursion
    (mouse-set-point click)
    (if (yafolding-get-overlays (line-beginning-position)
                                (+ 1 (line-end-position)))
        (define-key-after menu [yafolding-show-block]
          '(menu-item "Show block"
                      (lambda (click) (interactive "e")
                        (save-excursion
                          (mouse-set-point click)
                          (yafolding-show-element)))))
      (define-key-after menu [yafolding-hide-block]
        '(menu-item "Hide block"
                    (lambda (click) (interactive "e")
                      (save-excursion
                        (mouse-set-point click)
                        (yafolding-hide-element)))))))
  (define-key-after menu [hs-separator]
    menu-bar-separator)
  menu)


(context-menu-mode t)
```

Now, it works like a charm! (check screenshot)

![image](https://github.com/yoshiki/yaml-mode/assets/549126/d0688742-a147-45d6-aadb-15370733fb67)
